version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: traveltracker_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: traveltracker
      POSTGRES_PASSWORD: traveltrackerpassword
      POSTGRES_DB: travel_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U traveltracker -d travel_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local