version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: traveltracker_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: traveltracker
      POSTGRES_PASSWORD: traveltrackerpassword
      POSTGRES_DB: travel_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: traveltracker_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
    driver: local
  redis_data: